# Generated by Django 3.2 on 2021-05-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0003_auto_20210513_2316'),
        ('ourapp', '0006_alter_grade_grade'),
    ]

    operations = [
    ]
